spring:
  application:
    name: ridesharing-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/rideshare_db
    username: postgres
    password: fw18_0433
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: rideshare-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: tusharsamaniya02@gmail.com
    password: jdmv gxgk thrc wzbg 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

  app:
    name: RideShare
    support-email: tusharsamaniya02@gmail.com

server:
  port: 8081